name = "workers"
main = "src/index.ts"
compatibility_date = "2023-02-07"

kv_namespaces = [
  { binding = "kinds", id = "53c969db21a24e9b8e1bb0e0d1e11ef5", preview_id = "31baa22ab44e4d12abcbb9c446f6dbbe" }
]
